modLoader = "javafml"
loaderVersion = "${loader_version_range}"
issueTrackerURL = "https://github.com/lap2ka/nowheel/issues"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://modrinth.com/mod/create-nowheel"
authors="Lap2ka"
logoFile="icon.png"
description = '''
Boost performance in Create using Occlusion Culling
'''

[[mixins]]
config = "nowheel.mixins.json"

[[dependencies.${ mod_id }]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${ mod_id }]]
modId = "create"
type = "required"
versionRange = "[6.0.10,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${ mod_id }]]
modId = "entityculling"
type = "required"
versionRange = "[1.9,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${ mod_id }]]
modId = "cloth_config"
type = "optional"
versionRange = "[15,)"
ordering = "AFTER"
side = "CLIENT"
