org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

mod_id=nowheel
mod_name=Nowheel
mod_license=MIT
mod_version=2.1.0
mod_description=A lightweight optimization mod for Create, unifying Flywheel and Entity Culling to improve frame rates, reduce micro-stutter, and fix bugs.
mod_group_id=dev.lapt.nowheel

modrinth_id=c47YxuuI
curseforge_id=1544167
